Repository kubermatic/operating-system-manager, pull requests merged in 2021-11, with the labels that each got.

#49 Add documentation for OSM
  CONTRIBUTING.md
  README.md
  docs/images/architecture-osm-air-gapped.png
  docs/images/architecture-osm.png
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L

#55 New OWNER
  OWNERS_ALIASES
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#58 Add waleed to project owners
  OWNERS_ALIASES
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#57 Refactor osm cloud-config
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/cloud_provider.go
  pkg/controllers/osc/resources/operating_system_config.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#59 Minor fixes for osp-ubuntu-20.04
  examples/osp-ubuntu-20.04.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#60 Fix cluster dns ips
  cmd/osm-controller/main.go
  examples/osp-ubuntu-20.04.yaml
  hack/run-operating-system-manager.sh
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-docker.yaml
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-docker.yaml
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#54 Load in cluster config
  .gitignore
  cmd/osm-controller/main.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S

#50 Support for flatcar in OSM
  .gitignore
  .golangci.yml
  .prow.yaml
  .wwhrd.yml
  README.md
  charts/crd/crd-operating-system-config.yaml
  charts/crd/crd-operating-system-profile.yaml
  cmd/osm-controller/main.go
  examples/osp-flatcar-aws.yaml
  go.mod
  go.sum
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/resources/secrets.go
  pkg/controllers/osc/testdata/osc-flatcar-2605.22.1-aws-containerd.yaml
  pkg/controllers/osc/testdata/osp-flatcar-2605.22.1.yaml
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
  pkg/controllers/osc/testdata/secret-flatcar-2605.22.1-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-docker.yaml
  pkg/crd/osm/v1alpha1/common_types.go
  pkg/crd/osm/v1alpha1/operatingsystemconfig_types.go
  pkg/crd/osm/v1alpha1/operatingsystemprofile_types.go
  pkg/crd/osm/v1alpha1/zz_generated.deepcopy.go
  pkg/generator/convertor.go
  pkg/generator/generator.go
  pkg/generator/generator_test.go
  pkg/generator/provisioner.go
  pkg/providerconfig/amzn2/amzn.go
  pkg/providerconfig/centos/centos.go
  pkg/providerconfig/flatcar/flatcar.go
  pkg/providerconfig/rhel/rhel.go
  pkg/providerconfig/sles/sles.go
  pkg/providerconfig/ubuntu/ubuntu.go
Labels: lgtm, release-note, approved, dco-signoff: yes, size/XXL

#69 Make encoding field optional in OSP
  charts/crd/crd-operating-system-config.yaml
  charts/crd/crd-operating-system-profile.yaml
  examples/osp-flatcar-aws.yaml
  pkg/crd/osm/v1alpha1/common_types.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S

#72 OSC namespace replaced by cloud-init-settings
  cmd/osm-controller/main.go
  pkg/controllers/osc/osc_controller.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#73 Centos support
  charts/crd/crd-operating-system-config.yaml
  charts/crd/crd-operating-system-profile.yaml
  examples/osp-centos.yaml
  hack/run-operating-system-manager.sh
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/testdata/osc-flatcar-2605.22.1-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-2605.22.1-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-docker.yaml
  pkg/crd/osm/v1alpha1/common_types.go
  pkg/providerconfig/types.go
Labels: size/XL, lgtm, release-note, approved, dco-signoff: yes

#68 Add support for custom proxy
  cmd/osm-controller/main.go
  examples/osp-flatcar-aws.yaml
  examples/osp-ubuntu-20.04.yaml
  hack/update-fixtures.sh
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-2605.22.1-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-docker.yaml
  pkg/controllers/osc/testdata/osp-flatcar-2605.22.1.yaml
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
  pkg/controllers/osc/testdata/secret-flatcar-2605.22.1-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-docker.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/XXL

#76 add amazon linux support
  examples/osp-amzn-linux.yaml
  hack/run-operating-system-manager.sh
Labels: size/XL, lgtm, release-note, approved, dco-signoff: yes

#71 Cloud config generation
  .golangci.yml
  cmd/osm-controller/main.go
  go.mod
  pkg/cloudprovider/aws/provider.go
  pkg/cloudprovider/aws/types/cloudconfig.go
  pkg/cloudprovider/aws/types/cloudconfig_test.go
  pkg/cloudprovider/aws/types/types.go
  pkg/cloudprovider/azure/provider.go
  pkg/cloudprovider/azure/types/cloudconfig.go
  pkg/cloudprovider/azure/types/cloudconfig_test.go
  pkg/cloudprovider/azure/types/types.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/gce/provider.go
  pkg/cloudprovider/gce/types/cloudconfig.go
  pkg/cloudprovider/gce/types/cloudconfig_test.go
  pkg/cloudprovider/gce/types/types.go
  pkg/cloudprovider/kubevirt/provider.go
  pkg/cloudprovider/kubevirt/types/cloudconfig.go
  pkg/cloudprovider/kubevirt/types/cloudconfig_test.go
  pkg/cloudprovider/kubevirt/types/types.go
  pkg/cloudprovider/openstack/provider.go
  pkg/cloudprovider/openstack/types/cloudconfig.go
  pkg/cloudprovider/openstack/types/cloudconfig_test.go
  pkg/cloudprovider/openstack/types/types.go
  pkg/cloudprovider/vsphere/provider.go
  pkg/cloudprovider/vsphere/types/cloudconfig.go
  pkg/cloudprovider/vsphere/types/cloudconfig_test.go
  pkg/cloudprovider/vsphere/types/types.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/cloud_provider.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/osp-flatcar.yaml
  pkg/controllers/osc/testdata/secret-flatcar-2605.22.1-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-docker.yaml
  pkg/crd/osm/v1alpha1/common_types.go
  pkg/providerconfig/config/config.go
  pkg/providerconfig/config/types/types.go
Labels: lgtm, release-note, approved, dco-signoff: yes, size/XXL

#78 Retrieving only OSCs related to specific MD
  pkg/controllers/osc/osc_controller.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S

#81 Cloud-init modules support
  charts/crd/crd-operating-system-config.yaml
  charts/crd/crd-operating-system-profile.yaml
  hack/update-codegen.sh
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-docker.yaml
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-docker.yaml
  pkg/crd/client/clientset/versioned/clientset.go
  pkg/crd/client/clientset/versioned/doc.go
  pkg/crd/client/clientset/versioned/fake/clientset_generated.go
  pkg/crd/client/clientset/versioned/fake/doc.go
  pkg/crd/client/clientset/versioned/fake/register.go
  pkg/crd/client/clientset/versioned/scheme/doc.go
  pkg/crd/client/clientset/versioned/scheme/register.go
  pkg/crd/client/clientset/versioned/typed/osm/v1alpha1/doc.go
  pkg/crd/client/clientset/versioned/typed/osm/v1alpha1/fake/doc.go
  pkg/crd/client/clientset/versioned/typed/osm/v1alpha1/fake/fake_operatingsystemconfig.go
  pkg/crd/client/clientset/versioned/typed/osm/v1alpha1/fake/fake_operatingsystemprofile.go
  pkg/crd/client/clientset/versioned/typed/osm/v1alpha1/fake/fake_osm_client.go
  pkg/crd/client/clientset/versioned/typed/osm/v1alpha1/generated_expansion.go
  pkg/crd/client/clientset/versioned/typed/osm/v1alpha1/operatingsystemconfig.go
  pkg/crd/client/clientset/versioned/typed/osm/v1alpha1/operatingsystemprofile.go
  pkg/crd/client/clientset/versioned/typed/osm/v1alpha1/osm_client.go
  pkg/crd/client/informers/externalversions/factory.go
  pkg/crd/client/informers/externalversions/generic.go
  pkg/crd/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/crd/client/informers/externalversions/osm/interface.go
  pkg/crd/client/informers/externalversions/osm/v1alpha1/interface.go
  pkg/crd/client/informers/externalversions/osm/v1alpha1/operatingsystemconfig.go
  pkg/crd/client/informers/externalversions/osm/v1alpha1/operatingsystemprofile.go
  pkg/crd/client/listers/osm/v1alpha1/expansion_generated.go
  pkg/crd/client/listers/osm/v1alpha1/operatingsystemconfig.go
  pkg/crd/client/listers/osm/v1alpha1/operatingsystemprofile.go
  pkg/crd/osm/v1alpha1/common_types.go
  pkg/crd/osm/v1alpha1/operatingsystemconfig_types.go
  pkg/crd/osm/v1alpha1/operatingsystemprofile_types.go
  pkg/crd/osm/v1alpha1/zz_generated.deepcopy.go
  pkg/generator/generator.go
  pkg/generator/generator_test.go
Labels: lgtm, release-note, approved, dco-signoff: yes, size/XXL

#74 Fixes for flatcar OSP
  examples/osp-flatcar.yaml
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osp-flatcar.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L

#84 Support RHEL in OSM
  cmd/osm-controller/main.go
  examples/osp-rhel.yaml
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/resources/operating_system_config.go
Labels: size/XL, lgtm, release-note, approved, dco-signoff: yes

#75 Osp ubuntu improvements
  cmd/osm-controller/main.go
  examples/osp-ubuntu.yaml
  hack/run-operating-system-manager.sh
  pkg/cloudprovider/cloudprovider.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, priority/normal, size/L
