Repository kubermatic/operating-system-manager, pull requests merged in 2021-12, with the labels that each got.

#88 Minor improvements and fixes for CentOS OSP
  examples/osp-amzn-linux.yaml
  examples/osp-centos.yaml
  examples/osp-flatcar.yaml
  examples/osp-rhel.yaml
  examples/osp-ubuntu.yaml
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#89 Hotfix for invalid templating in OSP
  examples/osp-amzn-linux.yaml
  examples/osp-centos.yaml
  examples/osp-flatcar.yaml
  examples/osp-rhel.yaml
  examples/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S

#90 Osm enhancements
  cmd/osm-controller/main.go
  examples/osp-amzn-linux.yaml
  examples/osp-centos.yaml
  examples/osp-rhel.yaml
  examples/osp-ubuntu.yaml
  hack/run-operating-system-manager.sh
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osp-rhel.yaml
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
  pkg/providerconfig/types.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L

#92 Refactor all default OSPs
  cmd/osm-controller/main.go
  examples/osp-amzn-linux.yaml
  examples/osp-centos.yaml
  examples/osp-flatcar.yaml
  examples/osp-rhel.yaml
  examples/osp-sles.yaml
  examples/osp-ubuntu.yaml
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osp-rhel.yaml
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L

#93 Add missing `usr_local_bin` variable in the setup script
  examples/osp-amzn-linux.yaml
  examples/osp-centos.yaml
  examples/osp-rhel.yaml
  hack/run-operating-system-manager.sh
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#108 Introduce CI/CD for OSM
  .prow.yaml
  Dockerfile
  Makefile
  hack/ci/ci-download-gocache.sh
  hack/ci/ci-upload-gocache.sh
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L

#109 fix osm post-submits tests
  .prow.yaml
  Makefile
  hack/ci/download-gocache.sh
  hack/ci/upload-gocache.sh
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#110 Fix osm upload-gocache.sh script
  hack/ci/upload-gocache.sh
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#111 Add retry function to lib.sh
  hack/lib.sh
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#112 Refactor docker push in makefile
  Makefile
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#113 Default osp creation
  .prow.yaml
  charts/osps/default/osp-amzn-linux.yaml
  charts/osps/default/osp-centos.yaml
  charts/osps/default/osp-flatcar.yaml
  charts/osps/default/osp-rhel.yaml
  charts/osps/default/osp-sles.yaml
  charts/osps/default/osp-ubuntu.yaml
  charts/osps/default_osps.go
  codegen/reconcile/main.go
  go.mod
  go.sum
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  pkg/controllers/osp/osp_controller.go
  pkg/crd/osm/v1alpha1/zz_generated.deepcopy.go
  pkg/resources/reconciling/ensure_test.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: size/XL, lgtm, release-note, approved, dco-signoff: yes

#106 Webhooks for OSM
  Dockerfile
  README.md
  cmd/osm-controller/main.go
  cmd/webhook/main.go
  deploy/crd/crd-operating-system-config.yaml
  deploy/crd/crd-operating-system-profile.yaml
  deploy/operating-system-manager-webhook.yaml
  deploy/operating-system-manager.yaml
  deploy/osps/default/osp-amzn-linux.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  deploy/osps/default_osps.go
  go.mod
  go.sum
  hack/run-operating-system-manager.sh
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-crds-openapi.sh
  pkg/admission/admission.go
  pkg/admission/machinedeployments.go
  pkg/admission/machinedeployments_test.go
  pkg/admission/machinedeployments_validation.go
  pkg/admission/operatingsystemconfigs.go
  pkg/admission/operatingsystemconfigs_test.go
  pkg/admission/operatingsystemconfigs_validation.go
  pkg/admission/operatingsystemprofiles.go
  pkg/admission/operatingsystemprofiles_test.go
  pkg/admission/operatingsystemprofiles_validation.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/resources/secrets.go
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-docker.yaml
  pkg/controllers/osp/osp_controller.go
  pkg/crd/osm/v1alpha1/common_types.go
  pkg/crd/osm/v1alpha1/operatingsystemprofile_types.go
Labels: lgtm, release-note, approved, dco-signoff: yes, size/XXL

#115 Document compatibility matrix which represents support OS and cloud providers
  README.md
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-ubuntu.yaml
  docs/compatibility-matrix.md
Labels: documentation, release-note-none, kind/documentation, lgtm, approved, dco-signoff: yes, size/S

#116 Hotfixes for OSM
  .dockerignore
  Makefile
  cmd/osm-controller/main.go
  deploy/operating-system-manager.yaml
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L
