Repository kubermatic/operating-system-manager, pull requests merged in 2022-05, with the labels that each got.

#162 Golang 1.18
  .golangci.yml
  .prow.yaml
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
Labels: size/XL, lgtm, release-note, approved, dco-signoff: yes

#164 Support for kubernetes 1.24 and containerd 1.5
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-centos8.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  docs/compatibility-matrix.md
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/L

#161 rh_subscription module addition
  deploy/osps/default/osp-rhel.yaml
  go.mod
  go.sum
  pkg/cloudprovider/kubevirt/provider.go
  pkg/cloudprovider/kubevirt/types/types.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/providerconfig/rhel/rhel.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L

#166 Support node registry credentials with docker
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-centos8.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  go.mod
  go.sum
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/L
