Repository kubermatic/operating-system-manager, pull requests merged in 2022-02, with the labels that each got.

#137 Change baseurl to vault.centos.org for CentOS 8
  deploy/osps/default/osp-centos8.yaml
Labels: size/XL, lgtm, release-note, approved, dco-signoff: yes

#139 Refactor webhooks for OSM
  cmd/webhook/main.go
  pkg/admission/admission.go
  pkg/admission/machinedeployment/validation/validation.go
  pkg/admission/machinedeployment/validation/validation_test.go
  pkg/admission/machinedeployments.go
  pkg/admission/operatingsystemconfig/validation/validation.go
  pkg/admission/operatingsystemconfig/validation/validation_test.go
  pkg/admission/operatingsystemconfigs.go
  pkg/admission/operatingsystemconfigs_test.go
  pkg/admission/operatingsystemconfigs_validation.go
  pkg/admission/operatingsystemprofile/validation/validation.go
  pkg/admission/operatingsystemprofile/validation/validation_test.go
  pkg/admission/operatingsystemprofiles.go
  pkg/admission/operatingsystemprofiles_test.go
  pkg/admission/operatingsystemprofiles_validation.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XXL

#143 Revert "Refactor webhooks for OSM (#139)"
  cmd/webhook/main.go
  pkg/admission/admission.go
  pkg/admission/machinedeployments.go
  pkg/admission/machinedeployments_test.go
  pkg/admission/machinedeployments_validation.go
  pkg/admission/operatingsystemconfig/validation/validation.go
  pkg/admission/operatingsystemconfig/validation/validation_test.go
  pkg/admission/operatingsystemconfigs.go
  pkg/admission/operatingsystemconfigs_test.go
  pkg/admission/operatingsystemconfigs_validation.go
  pkg/admission/operatingsystemprofile/validation/validation.go
  pkg/admission/operatingsystemprofile/validation/validation_test.go
  pkg/admission/operatingsystemprofiles.go
  pkg/admission/operatingsystemprofiles_test.go
  pkg/admission/operatingsystemprofiles_validation.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XXL

#141 Adding the proper e2e tests infrastructure to start adding tests
  .prow.yaml
  Makefile
  cmd/webhook/main.go
  deploy/cluster-role.yaml
  deploy/operating-system-manager-webhook.yaml
  deploy/operating-system-manager.yaml
  deploy/role.yaml
  hack/ci/run-e2e-tests.sh
  hack/ci/setup-kind-cluster.sh
  hack/ci/setup-osm-in-kind.sh
  hack/ci/testdata/machine-controller.yaml
  hack/ci/testdata/webhook-certificate.cnf
  hack/lib.sh
  hack/verify-boilerplate.sh
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XXL

#149 Fix encoding for file content in secrets
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker.yaml
  pkg/generator/generator.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S
