Repository kubermatic/operating-system-manager, pull requests merged in 2022-06, with the labels that each got.

#167 Support configuring MaxPods
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-centos8.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  go.mod
  go.sum
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker.yaml
Labels: lgtm, size/M, release-note, approved, dco-signoff: yes

#168 Sync the OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#169 Adjust DynamicKubeletConfig=true based on k8s version
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-centos8.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker.yaml
Labels: lgtm, size/M, release-note, approved, dco-signoff: yes

#171 Initialize the node-containerd-registry-mirrors flag
  cmd/osm-controller/main.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#173 Support for OSC rotation when machine deployment is updated
  .golangci.yml
  .prow.yaml
  hack/run-operating-system-manager.sh
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/L

#177 Support yum repos cloud-init module
  deploy/crd/crd-operating-system-config.yaml
  deploy/crd/crd-operating-system-profile.yaml
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-cloud-init-modules.yaml
  pkg/crd/osm/v1alpha1/common_types.go
  pkg/crd/osm/v1alpha1/zz_generated.deepcopy.go
  pkg/generator/generator.go
  pkg/generator/generator_test.go
Labels: lgtm, release-note, approved, dco-signoff: yes, size/XXL

#179 fix: File permissions are not properly rendered
  deploy/crd/crd-operating-system-config.yaml
  deploy/crd/crd-operating-system-profile.yaml
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-centos8.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/admission/operatingsystemconfig/validation/validation_test.go
  pkg/admission/operatingsystemprofile/validation/validation_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker.yaml
  pkg/crd/osm/v1alpha1/common_types.go
  pkg/crd/osm/v1alpha1/zz_generated.deepcopy.go
  pkg/generator/generator.go
  pkg/generator/generator_test.go
Labels: size/XL, lgtm, approved, dco-signoff: yes, release-note-action-required

#174 Minor refactor
  .dockerignore
  .prow/postsubmits.yaml
  .prow/verify.yaml
  .yamllint.conf
  Dockerfile
  Makefile
  OWNERS
  OWNERS_ALIASES
  cmd/osm-controller/main.go
  deploy/cloud-init-settings.yaml
  deploy/role.yaml
  go.mod
  go.sum
  hack/ci/run-e2e-tests.sh
  hack/ci/setup-kind-cluster.sh
  hack/ci/setup-osm-in-kind.sh
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  pkg/admission/machinedeployment/validation/validation_test.go
  pkg/cloudprovider/aws/types/cloudconfig.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/gce/provider.go
  pkg/cloudprovider/gce/types/cloudconfig.go
  pkg/cloudprovider/kubevirt/provider.go
  pkg/cloudprovider/openstack/provider.go
  pkg/cloudprovider/openstack/types/cloudconfig.go
  pkg/cloudprovider/vsphere/provider.go
  pkg/cloudprovider/vsphere/types/cloudconfig.go
  pkg/controllers/osc/resources/operating_system_config.go
Labels: release-note-none, size/XL, lgtm, approved, dco-signoff: yes

#180 Fix scheme for controller manager & refactor way to get API server token for bootstrap script
  cmd/osm-controller/main.go
  deploy/cloud-init-settings.yaml
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemconfigs.yaml
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemprofiles.yaml
  deploy/role.yaml
  pkg/bootstrap/cloud_init_settings.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-provisioning.yaml
  pkg/crd/osm/v1alpha1/operatingsystemconfig_types.go
  pkg/crd/osm/v1alpha1/operatingsystemprofile_types.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XXL, sig/osm
