Repository kubermatic/operating-system-manager, pull requests merged in 2022-03, with the labels that each got.

#142 Refactor OSP templates
  Makefile
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-centos8.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/XXL

#154 Domain name is not required when using application credentials
  pkg/cloudprovider/openstack/types/cloudconfig.go
  pkg/cloudprovider/openstack/types/cloudconfig_test.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#155 Disable firewalld on supported OSes
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-centos8.yaml
  deploy/osps/default/osp-rhel.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S
