Repository kubermatic/operating-system-manager, pull requests merged in 2022-01, with the labels that each got.

#117 Fix docker image build and publish step
  Makefile
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#119 Support for Kubelet flags
  deploy/osps/default/osp-amzn-linux.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  go.mod
  go.sum
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-docker.yaml
  pkg/controllers/osc/testdata/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osp-rhel.yaml
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-docker.yaml
Labels: size/XL, lgtm, release-note, approved, dco-signoff: yes

#120 Fix typo in OSP CRD
  deploy/crd/crd-operating-system-profile.yaml
  pkg/crd/osm/v1alpha1/operatingsystemprofile_types.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#121 Fix secrets handling in OSM
  pkg/controllers/osc/osc_controller.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#122 Fix namespace for secret cleanup
  pkg/controllers/osc/osc_controller.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS, sig/osm

#126 Remove Kubelet Bootstrap Kubeconfig
  deploy/osps/default/osp-amzn-linux.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-docker.yaml
  pkg/controllers/osc/testdata/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osp-rhel.yaml
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-docker.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L

#127 Fix name for amazon linux OSP
  deploy/osps/default/osp-amzn2.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#128 Use semver versioning for default OperatingSystemProfiles
  deploy/crd/crd-operating-system-profile.yaml
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/crd/osm/v1alpha1/operatingsystemprofile_types.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S

#130 Fix sample OSP link in README
  README.md
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS

#133 Consume config variable resolver from machine-controller
  go.mod
  go.sum
  pkg/cloudprovider/aws/types/types.go
  pkg/cloudprovider/azure/types/types.go
  pkg/cloudprovider/gce/types/types.go
  pkg/cloudprovider/kubevirt/types/types.go
  pkg/cloudprovider/openstack/types/types.go
  pkg/cloudprovider/vsphere/types/types.go
  pkg/providerconfig/config/config.go
  pkg/providerconfig/config/types/types.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L

#132 Improve handling of CA cert
  cmd/osm-controller/main.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/kube-config.yaml
  pkg/util/certificate/certificate.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L

#135 Support for Kubelet feature gates
  cmd/osm-controller/main.go
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-20.04-aws-docker.yaml
  pkg/controllers/osc/testdata/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osp-rhel.yaml
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-20.04-aws-docker.yaml
  pkg/util/certificate/certificate.go
Labels: lgtm, release-note, approved, dco-signoff: yes, size/L

#134 Support for Nutanix cloud provider
  deploy/crd/crd-operating-system-config.yaml
  deploy/crd/crd-operating-system-profile.yaml
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/cloudprovider/cloudprovider.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osp-rhel.yaml
  pkg/controllers/osc/testdata/osp-ubuntu-20.04.yaml
  pkg/crd/osm/v1alpha1/common_types.go
Labels: lgtm, size/M, release-note, approved, dco-signoff: yes
