Repository kubermatic/operating-system-manager, pull requests merged in 2022-08, with the labels that each got.

#196 Fix for handling dualstack and all cases for passing node-ip parameter to kubelet
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm

#198 set IPv6AcceptRA=true for Flatcar
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm

#201 Unified PR template update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes, sig/osm

#200 Disable network config with cloud-init for Hetzner
  deploy/osps/default/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS, sig/osm

#205 Invalidate Kubelet bootstrap token
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/bootstrap/kubeconfig.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/bug, lgtm, kind/api-change, release-note, approved, dco-signoff: yes, size/L, sig/osm

#206 enable DHCPv6 in RockyLinux
  deploy/osps/default/osp-rockylinux.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS, sig/osm

#208 cleaning up kubelet bootstrapping config
  pkg/bootstrap/kubeconfig.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes, sig/osm

#204 Update documentation for OSM
  README.md
  docs/images/architecture-osm-air-gapped.png
Labels: release-note-none, kind/documentation, lgtm, size/M, approved, dco-signoff: yes, sig/osm

#209 Fixes for Nutanix
  pkg/cloudprovider/cloudprovider.go
Labels: kind/bug, release-note-none, lgtm, approved, dco-signoff: yes, size/XS, sig/osm

#210 Enable iscsid for ubuntu on nutanix
  deploy/osps/default/osp-ubuntu.yaml
Labels: kind/bug, release-note-none, lgtm, approved, dco-signoff: yes, size/XS, sig/osm

#212 Bump OperatingSystemProfiles to v1.0.0
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: kind/feature, release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm

#213 Bump machine-controller dependency to v1.53.0
  go.mod
  go.sum
Labels: release-note-none, lgtm, kind/api-change, approved, dco-signoff: yes, size/XS, sig/osm
