Repository kubermatic/operating-system-manager, pull requests merged in 2022-11, with the labels that each got.

#232 Fix static network rendering for flatcar
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
Labels: kind/bug, release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm, docs/none

#233 Upgrade to Go 1.19.3
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
Labels: kind/feature, lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm, docs/none

#236 Restart Containerd/Docker to ensure that drop-in configuration is picked up
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
Labels: kind/bug, release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm, docs/none

#227 Update MachineDeployment webhook to mutate OSP annotation and move validation to osc-controller loop
  cmd/webhook/main.go
  deploy/operating-system-manager-webhook.yaml
  go.mod
  go.sum
  pkg/admission/machinedeployment/mutation/mutation.go
  pkg/admission/machinedeployment/mutation/mutation_test.go
  pkg/admission/machinedeployment/validation/validation.go
  pkg/admission/machinedeployment/validation/validation_test.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/generator/generator.go
  pkg/generator/generator_test.go
Labels: kind/feature, size/XL, lgtm, release-note, approved, dco-signoff: yes, sig/osm, docs/none

#237 Support for Custom CA Certificates
  cmd/osm-controller/main.go
  go.mod
  go.sum
  pkg/controllers/osc/resources/operating_system_config.go
Labels: kind/feature, lgtm, release-note, approved, dco-signoff: yes, size/L, sig/osm, docs/tbd

#238 remove KubeletCloudProviderConfig func
  pkg/cloudprovider/cloudprovider.go
  pkg/controllers/osc/resources/operating_system_config.go
Labels: kind/bug, lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm, docs/none

#239 Remove CloudConfig file from vsphere machines
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm, docs/none

#240 Add missing check that only sets OSP annotation on MachineDeployments if it's unset
  pkg/admission/machinedeployment/mutation/mutation.go
Labels: kind/bug, release-note-none, lgtm, size/M, approved, dco-signoff: yes, sig/osm, kind/regression, docs/none

#241 Hotfix: CA Bundle flag
  cmd/osm-controller/main.go
Labels: kind/bug, release-note-none, lgtm, approved, dco-signoff: yes, size/XS, sig/osm, docs/none

#243 Update Developer Certificate of Origin
  CONTRIBUTING.md
  DCO
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XS, sig/osm, kind/chore, docs/none
