Repository kubermatic/operating-system-manager, pull requests merged in 2022-07, with the labels that each got.

#183 [release/v0.4] Support yum repos cloud-init module
  cmd/osm-controller/main.go
  deploy/crd/crd-operating-system-config.yaml
  deploy/crd/crd-operating-system-profile.yaml
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-cloud-init-modules.yaml
  pkg/crd/osm/v1alpha1/common_types.go
  pkg/crd/osm/v1alpha1/zz_generated.deepcopy.go
  pkg/generator/generator.go
  pkg/generator/generator_test.go
Labels: release-note, approved, dco-signoff: yes, size/XXL

#181 Bump docker version to 20.10 in default OperatingSystemProfiles
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-centos8.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  docs/compatibility-matrix.md
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker.yaml
Labels: lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm

#191 Use the correct field for the external cloud provider flag
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-centos8.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm

#189 Avoid setting hostname in provisioning configuration
  deploy/osps/default/osp-centos8.yaml
  pkg/admission/machinedeployment/validation/validation.go
  pkg/admission/machinedeployment/validation/validation_test.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-bootstrap.yaml
  pkg/generator/generator.go
  pkg/generator/generator_test.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/XXL, sig/osm

#190 Add annotation to specify custom namespace for OSP
  cmd/osm-controller/main.go
  pkg/admission/machinedeployment/validation/validation.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
Labels: lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm

#193 Remove the usage of APIReader for fetching OSP
  cmd/osm-controller/main.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm

#192 Fixes and enhancements
  deploy/certificate.yaml
  deploy/cloud-init-settings.yaml
  deploy/operating-system-manager-webhook.yaml
  deploy/operating-system-manager.yaml
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  deploy/rbac-controller.yaml
  deploy/rbac-webhook.yaml
  docs/compatibility-matrix.md
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
  pkg/generator/generator.go
  pkg/generator/generator_test.go
  pkg/generator/provisioner.go
  pkg/providerconfig/common.go
Labels: lgtm, release-note, approved, dco-signoff: yes, size/XXL, sig/osm

#195 Add resolv-conf flag to flatcar
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm
