Repository kubermatic/operating-system-manager, pull requests merged in 2023-10, with the labels that each got.

#312 Remove k8s 1.25 from supported versions
  docs/compatibility-matrix.md
Labels: kind/cleanup, lgtm, release-note, approved, dco-signoff: yes, size/XS, sig/osm, docs/tbd

#314 Remove duplicate file resource from flatcar OSP
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
Labels: kind/bug, lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm, docs/none

#318 [release/v1.3] Remove duplicate file resource from flatcar OSP
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
Labels: kind/bug, lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm

#319 [release/v1.2] Remove duplicate file resource from flatcar OSP
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
Labels: kind/bug, lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm

#320 [release/v1.1] Remove duplicate file resource from flatcar OSP
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
Labels: kind/bug, lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm

#315 Bump default OSP versions to 1.3.3
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm, kind/chore, docs/none

#316 [release/v1.2] Update default OSP versions to v1.2.3
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm, kind/chore

#324 Drop in-tree support for OpenStack
  pkg/cloudprovider/cloudprovider.go
Labels: kind/cleanup, lgtm, release-note, approved, dco-signoff: yes, size/XS, sig/osm, docs/none

#326 Remove mentions of Zenhub
  README.md
Labels: release-note-none, kind/cleanup, lgtm, approved, dco-signoff: yes, size/XS, sig/osm, docs/none

#327 Drop centos support for Hetzner
  deploy/osps/default/osp-centos.yaml
  docs/compatibility-matrix.md
Labels: kind/cleanup, lgtm, release-note, approved, dco-signoff: yes, size/XS, sig/osm, docs/none

#325 Upgrade to Go 1.21.3
  .golangci.yml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
  pkg/controllers/osc/osc_reconciler_test.go
Labels: lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm, kind/chore, docs/none
