Repository kubermatic/operating-system-manager, pull requests merged in 2023-01, with the labels that each got.

#248 Update to k8s v1.26.0, container-runtime v0.14.1
  .prow/verify.yaml
  NOTICE
  go.mod
  go.sum
  hack/header.txt
  hack/verify-licenses.sh
  pkg/crd/osm/v1alpha1/zz_generated.deepcopy.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L, sig/osm, kind/chore, docs/none

#250 Drop support for docker as container runtime
  cmd/osm-controller/main.go
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  docs/compatibility-matrix.md
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-provisioning.yaml
Labels: kind/cleanup, lgtm, release-note, approved, dco-signoff: yes, size/XXL, sig/osm, docs/provided

#252 Pin containerd to v1.6 for Amazon Linux
  deploy/osps/default/osp-amzn2.yaml
Labels: kind/feature, lgtm, release-note, approved, dco-signoff: yes, size/XS, sig/osm, docs/none

#251 Drop support for SLES
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemconfigs.yaml
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemprofiles.yaml
  deploy/osps/default/osp-sles.yaml
  hack/update-codegen.sh
  pkg/admission/machinedeployment/mutation/mutation.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/crd/osm/v1alpha1/common_types.go
  pkg/providerconfig/sles/sles.go
Labels: kind/cleanup, size/XL, lgtm, release-note, approved, dco-signoff: yes, sig/osm, docs/tbd

#254 Update enqueue conditions for OSP controller
  go.mod
  go.sum
  pkg/controllers/osp/osp_controller.go
  pkg/util/predicate/predicate.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes, sig/osm, kind/chore, docs/none

#255 Add new CRD for CustomOperatingSystemProfile
  .prow/verify.yaml
  hack/kkp/operatingsystemmanager.k8c.io_customoperatingsystemprofiles.yaml
  hack/update-crds-openapi.sh
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L, sig/osm, kind/chore, docs/none

#256 Update kubernetes-cni to v1.2.0
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/feature, lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm, docs/none

#257 Update cri-tools to v1.26.0
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/feature, lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm, docs/none

#258 Fix checksum checks for cri-tools
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: release-note-none, kind/cleanup, lgtm, size/M, approved, dco-signoff: yes, sig/osm, docs/none

#259 Update kubernetes-cni to v1.2.0 and cri-tools to v1.26.0
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  hack/lib.sh
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/feature, lgtm, release-note, approved, dco-signoff: yes, size/L, sig/osm

#260 [release/v0.4] Update containerd, docker, kubernetes-cni, and cri-tools
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-centos8.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  hack/lib.sh
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-docker.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-docker.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-docker.yaml
Labels: kind/bug, lgtm, release-note, approved, dco-signoff: yes, size/L

#261 [release/v0.3] Update containerd, docker, kubernetes-cni, and cri-tools
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-sles.yaml
  deploy/osps/default/osp-ubuntu.yaml
  hack/lib.sh
Labels: kind/bug, lgtm, release-note, approved, dco-signoff: yes, size/L
