Repository kubermatic/operating-system-manager, pull requests merged in 2023-12, with the labels that each got.

#332 Update dependencies and logger for webhook
  .prow/verify.yaml
  Dockerfile
  cmd/osm-controller/main.go
  cmd/webhook/main.go
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemconfigs.yaml
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemprofiles.yaml
  deploy/operating-system-manager-webhook.yaml
  deploy/operating-system-manager.yaml
  go.mod
  go.sum
  pkg/admission/machinedeployment/mutation/mutation.go
  pkg/admission/operatingsystemconfig/validation/validation.go
  pkg/admission/operatingsystemconfig/validation/validation_test.go
  pkg/admission/operatingsystemprofile/validation/validation.go
  pkg/admission/operatingsystemprofile/validation/validation_test.go
  pkg/cloudprovider/openstack/provider.go
  pkg/clusterinfo/configmap.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/resources/secrets.go
  pkg/controllers/osp/osp_controller.go
  pkg/crd/osm/v1alpha1/zz_generated.deepcopy.go
  pkg/generator/convertor.go
  pkg/log/zap.go
  pkg/test/util/log.go
Labels: size/XL, lgtm, release-note, approved, dco-signoff: yes, sig/osm, kind/chore, docs/none

#336 Add SIG Cluster Management as code owners
  OWNERS
  OWNERS_ALIASES
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm, kind/chore, docs/none

#338 [release/v1.4] Update to Go 1.21.5
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm, kind/chore

#339 [release/v1.3] Update to Go 1.20.12
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm, kind/chore

#337 Update to Go 1.21.5
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm, kind/chore, docs/none
