Repository kubermatic/operating-system-manager, pull requests merged in 2023-06, with the labels that each got.

#289 Update Golang to 1.20.5
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm, kind/chore, docs/none

#292 Update K8s dependencies to 1.27.2
  go.mod
  go.sum
  hack/kkp/operatingsystemmanager.k8c.io_customoperatingsystemprofiles.yaml
  pkg/admission/operatingsystemconfig/validation/validation_test.go
  pkg/admission/operatingsystemprofile/validation/validation_test.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osp/osp_controller.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L, sig/osm, kind/chore, docs/none

#294 Revert "Update K8s dependencies to 1.27.2 (#292)"
  go.mod
  go.sum
  hack/kkp/operatingsystemmanager.k8c.io_customoperatingsystemprofiles.yaml
  pkg/admission/operatingsystemconfig/validation/validation_test.go
  pkg/admission/operatingsystemprofile/validation/validation_test.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osp/osp_controller.go
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/L, sig/osm, docs/none

#295 Add documentation for release steps
  docs/release.md
Labels: release-note-none, kind/documentation, lgtm, approved, dco-signoff: yes, size/XS, sig/osm, docs/none

#297 Bump machine-controller dependency to v1.57.0
  go.mod
  go.sum
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm, kind/chore, docs/none
