Repository kubermatic/operating-system-manager, pull requests merged in 2023-04, with the labels that each got.

#283 Flatcar cloud-init OSP: fix setting up kernel for kubelet
  deploy/osps/default/osp-flatcar-cloud-init.yaml
Labels: kind/bug, release-note-none, lgtm, approved, dco-signoff: yes, size/S, needs-ok-to-test, sig/osm, docs/none

#284 Forbid users from using units with operating systems other than flatcar
  pkg/admission/operatingsystemprofile/validation/validation.go
Labels: kind/feature, release-note-none, lgtm, size/M, approved, dco-signoff: yes, sig/osm, docs/none

#285 Bump Golang version to 1.20.3
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm, kind/chore, docs/none

#286 [release/v1.2] Bump Golang to 1.19.8
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm, kind/chore
