Repository kubermatic/operating-system-manager, pull requests merged in 2024-10, with the labels that each got.

#419 Resolve DNS resolution issues for Hetzner on Ubuntu 24.04
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
Labels: kind/bug, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/S, docs/none

#420 Allow Ubuntu only for baremetal
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-rockylinux.yaml
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/XS, docs/none

#422 set OSP version to 1.6.0
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/S, docs/none

#423 Drop support for Kubernetes v1.28
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  docs/compatibility-matrix.md
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
Labels: kind/cleanup, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, docs/none
