Repository kubermatic/operating-system-manager, pull requests merged in 2024-02, with the labels that each got.

#349 Add edge cloud provider
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemconfigs.yaml
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemprofiles.yaml
  pkg/cloudprovider/cloudprovider.go
  pkg/controllers/osc/osc_controller.go
  pkg/crd/osm/v1alpha1/common_types.go
Labels: lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, docs/none

#350 Update generated CustomOperatingSystemProfile
  hack/kkp/operatingsystemmanager.k8c.io_customoperatingsystemprofiles.yaml
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/XS, kind/chore, docs/none

#351 Render machine name
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/osc_controller.go
  pkg/generator/generator.go
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/S, docs/none

#352 Upgrade to Go 1.22
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
  pkg/controllers/osc/osc_controller.go
Labels: lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/L, kind/chore, docs/none

#354 Drop capability to disable disablecloudproviders feature gate
  .prow/verify.yaml
  Makefile
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
Labels: release-note-none, kind/cleanup, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/L, docs/none

#353 Cloud-config is not required for external cloud providers
  pkg/cloudprovider/cloudprovider.go
  pkg/clusterinfo/configmap.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
  pkg/controllers/osp/osp_controller.go
Labels: kind/bug, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/L, docs/none

#356 [release/v1.3] Cloud-config is not required for external cloud providers
  .prow/verify.yaml
  Makefile
  pkg/cloudprovider/cloudprovider.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: kind/bug, lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm

#355 [release/v1.4] Cloud-config is not required for external cloud providers
  .prow/verify.yaml
  Makefile
  pkg/cloudprovider/cloudprovider.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: kind/bug, lgtm, size/M, release-note, approved, dco-signoff: yes, sig/osm

#357 Remove hard dependency on torcx, removed in Flatcar 3815.2.0
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
Labels: kind/bug, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/S, docs/none

#358 [release/v1.4] Remove hard dependency on torcx, removed in Flatcar 3815.2.0
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
Labels: kind/bug, lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm

#359 [release/v1.3] Remove hard dependency on torcx, removed in Flatcar 3815.2.0
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
Labels: kind/bug, lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm

#362 [release/v1.3] Prepare OSM v1.3.4
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm, kind/chore

#361 [release/v1.4] Prepare OSM v1.4.1
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm, kind/chore

#360 [release/v1.2] Remove hard dependency on torcx, removed in Flatcar 3815.2.0
  .prow/verify.yaml
  Makefile
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: kind/bug, lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm

#363 [release/v1.2] Prepare OSM v1.2.4
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, dco-signoff: yes, size/S, sig/osm, kind/chore

#365 Avoid second run of bootstrap script for flatcar with cloud-init
  deploy/osps/default/osp-flatcar-cloud-init.yaml
Labels: kind/bug, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/S, docs/none
