Repository kubermatic/operating-system-manager, pull requests merged in 2024-05, with the labels that each got.

#388 Run `cloud-init init --local` once on Azure to get provider configuration set up properly
  deploy/osps/default/osp-ubuntu.yaml
Labels: kind/bug, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/XS, kind/regression, docs/none

#390 [release/v1.5] Run `cloud-init init --local` once on Azure to get provider configuration set up properly
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/S

#389 [release/v1.4] Run `cloud-init init --local` once on Azure to get provider configuration set up properly
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm

#391 [release/v1.3] Run `cloud-init init --local` once on Azure to get provider configuration set up properly
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm

#392 [release/v1.2] Run `cloud-init init --local` once on Azure to get provider configuration set up properly
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: lgtm, release-note, approved, dco-signoff: yes, size/S, sig/osm

#393 Add Baremetal Provider
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/cloudprovider/cloudprovider.go
Labels: kind/feature, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/XS, docs/none
