Repository kubermatic/operating-system-manager, pull requests merged in 2024-04, with the labels that each got.

#374 Update golang to 1.22.2
  .golangci.yml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
Labels: lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, kind/chore, docs/none

#375 Update Kubernetes CNI to v1.4.1
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/feature, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/XXL, docs/none

#376 Support for Kubernetes 1.30
  docs/compatibility-matrix.md
  go.mod
  go.sum
  pkg/admission/machinedeployment/mutation/mutation.go
  pkg/admission/machinedeployment/mutation/mutation_test.go
  pkg/admission/operatingsystemconfig/validation/validation.go
  pkg/admission/operatingsystemprofile/validation/validation.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/generator/generator_test.go
Labels: kind/feature, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/L, docs/tbd

#377 Enable parallel image pulls for Kubelet
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/feature, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, docs/none

#378 Use the same cri-tools and kubernetes minor version
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/bug, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/L, docs/none

#379 Fix ownership of `/opt/cni`
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/bug, release-note-none, lgtm, size/M, approved, sig/cluster-management, dco-signoff: yes, docs/none

#385 [release/v1.2] Hotfix: cloud-init broken flags / bump version to 1.2.5 (#381)
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-bootstrap.yaml
Labels: lgtm, approved, dco-signoff: yes, size/L, release-note-action-required, sig/osm
