Repository kubermatic/operating-system-manager, pull requests merged in 2024-07, with the labels that each got.

#399 Fix support for ca-bundle
  cmd/osm-controller/main.go
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  go.mod
  go.sum
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/resources/operating_system_config.go
Labels: lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/L, docs/none, needs-release-testing

#400 Bump Go version to 1.22.5
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
Labels: lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, kind/chore, docs/none

#401 Remove k8s 1.27 support
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  docs/compatibility-matrix.md
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
Labels: kind/cleanup, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, docs/tbd

#402 fix: handle GPG key for Docker repo
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, docs/none

#404 Remove un-required exception from golangci
  .golangci.yml
Labels: release-note-none, kind/cleanup, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/XS, docs/none

#403 Update containerd to v1.7
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/feature, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, kind/chore, docs/none

#405 Fix docker GPG handling in ubuntu OSP
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/bug, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, docs/none

#406 Fix containerd installation
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/bug, release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/S, docs/none

#407 Use RHEL upstream docker repo instead of abandoned CentOS
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
Labels: kind/bug, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, kind/regression, docs/none
