Repository kubermatic/operating-system-manager, pull requests merged in 2024-03, with the labels that each got.

#368 Fix: Support vmtoolsd from $PATH
  deploy/osps/default/osp-flatcar.yaml
Labels: kind/bug, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/XS, needs-ok-to-test, docs/none

#369 Drop k8s 1.26 support
  docs/compatibility-matrix.md
Labels: kind/cleanup, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/XS, docs/provided

#371 Prepare v1.5.0 release
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/S, kind/chore, docs/none

#346 feat: add extra funcmap
  go.mod
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/util/funcmap/extra_funcs.go
Labels: kind/feature, lgtm, release-note, approved, sig/cluster-management, ok-to-test, dco-signoff: yes, size/L, docs/provided

#373 Bump dependencies
  .golangci.yml
  .prow/verify.yaml
  deploy/cloud-init-settings.yaml
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemconfigs.yaml
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemprofiles.yaml
  go.mod
  go.sum
  hack/kkp/operatingsystemmanager.k8c.io_customoperatingsystemprofiles.yaml
  hack/lib.sh
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
  pkg/bootstrap/kubeconfig.go
  pkg/bootstrap/kubeconfig_test.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/L, kind/chore, docs/none
