Repository kubermatic/operating-system-manager, pull requests merged in 2024-06, with the labels that each got.

#380 update to controller-runtime 0.18.3
  deploy/rbac-controller.yaml
  go.mod
  go.sum
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osp/osp_controller.go
Labels: lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/L, docs/none

#394 Bump Go version to 1.22.4
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
Labels: lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, kind/chore, docs/none

#395 Move container-runtime specific code to OSM
  cmd/osm-controller/main.go
  go.mod
  go.sum
  pkg/cloudprovider/aws/types/cloudconfig.go
  pkg/cloudprovider/gce/types/cloudconfig.go
  pkg/cloudprovider/openstack/types/cloudconfig.go
  pkg/cloudprovider/vsphere/types/cloudconfig.go
  pkg/containerruntime/config.go
  pkg/containerruntime/config_test.go
  pkg/containerruntime/containerd.go
  pkg/containerruntime/containerruntime.go
  pkg/containerruntime/flags.go
  pkg/controllers/osc/osc_controller.go
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/resources/operating_system_config.go
  pkg/util/ini/duration.go
  pkg/util/ini/escape.go
  pkg/util/ini/escape_test.go
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/XXL, kind/chore, docs/none

#396 fix(controller): handle error for invalid osp
  pkg/controllers/osc/osc_controller.go
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/XS, needs-ok-to-test, docs/none
