Repository kubermatic/operating-system-manager, pull requests merged in 2024-01, with the labels that each got.

#343 Use zap instead of klog for controller
  cmd/osm-controller/main.go
Labels: kind/feature, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, docs/none

#347 use external CCM for GCE
  pkg/cloudprovider/cloudprovider.go
Labels: lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/S, kind/chore, docs/none

#348 Bring back cloud-provider flag for Kubelet
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/osc_reconciler_test.go
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
Labels: release-note-none, lgtm, size/M, approved, sig/cluster-management, dco-signoff: yes, kind/chore, docs/none
