Repository kubermatic/operating-system-manager, pull requests merged in 2025-04, with the labels that each got.

#447 Bump Go version to 1.23.7
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/verify-licenses.sh
Labels: lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, kind/chore, docs/none

#450 [release/v1.5] bump OSP to 1.5.5
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-centos.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/S, kind/chore

#449 [release/v1.6] bump OSP to 1.6.4
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/S, kind/chore

#453 Use the gpg --no-tty option in the container runtime installation script
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/bug, release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/S, docs/none

#456 [release/v1.6] Use the gpg --yes option instead of --no-tty option in the container runtime installation script
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/bug, release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/S

#457 [release/v1.6] Bump OSP version to 1.6.5
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/S, kind/chore
