Repository kubermatic/operating-system-manager, pull requests merged in 2025-09, with the labels that each got.

#514 replace eth0 interface with fallback netplan match on Hetzner Ubuntu nodes
  deploy/osps/default/osp-ubuntu.yaml
Labels: kind/bug, release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/XS, docs/none

#512 Add support for k8s 1.34 and drop support for k8s 1.30
  .golangci.yml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemconfigs.yaml
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemprofiles.yaml
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  docs/compatibility-matrix.md
  go.mod
  go.sum
  hack/update-codegen.sh
  hack/update-crds-openapi.sh
  hack/update-fixtures.sh
  hack/verify-licenses.sh
  pkg/clusterinfo/configmap_test.go
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-osc-rhel-8.x-cloud-init-modules-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-bootstrap.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/feature, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/L, docs/provided

#516 Fix docker build argument with latest Go version
  Makefile
Labels: kind/bug, release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/XS, docs/none

#519 [release/v1.7] Fix IP assignment issues on Hetzner
  deploy/osps/default/osp-ubuntu.yaml
Labels: kind/bug, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes

#520 [release/v1.6] Fix IP assignment issues on Hetzner
  deploy/osps/default/osp-ubuntu.yaml
Labels: kind/bug, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes

#521 Drop --lock-file kubelet argument
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/cleanup, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes, docs/none

#523 [release/v1.6] Drop --lock-file kubelet argument
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/cleanup, lgtm, size/M, release-note, approved, sig/cluster-management, dco-signoff: yes

#510 chore: switch from drop-ins to drop_ins, fix: templating of DropIns
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemconfigs.yaml
  deploy/crd/operatingsystemmanager.k8c.io_operatingsystemprofiles.yaml
  hack/kkp/operatingsystemmanager.k8c.io_customoperatingsystemprofiles.yaml
  pkg/crd/osm/v1alpha1/common_types.go
  pkg/generator/generator.go
Labels: kind/bug, lgtm, size/M, release-note, approved, sig/cluster-management, ok-to-test, dco-signoff: yes, docs/none
