Repository kubermatic/operating-system-manager, pull requests merged in 2025-07, with the labels that each got.

#479 fix: fix hostname resolution on Flatcar nodes
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
Labels: lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/S, docs/none

#480 Add modprobe br_netfilter to OSPs
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-kubelet-configuration-containerd.yaml
  pkg/controllers/osc/testdata/osc-rhel-8.x-azure-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-containerd.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack-IPv6+IPv4.yaml
  pkg/controllers/osc/testdata/osc-ubuntu-aws-dualstack.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-kubelet-configuration-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-rhel-8.x-azure-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-containerd-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-IPv6+IPv4-provisioning.yaml
  pkg/controllers/osc/testdata/secret-ubuntu-aws-dualstack-provisioning.yaml
Labels: kind/feature, lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/S, docs/none

#483 [release/v1.5] fix: fix hostname resolution on Flatcar nodes
  deploy/osps/default/osp-flatcar.yaml
  pkg/controllers/osc/testdata/osc-flatcar-aws-containerd.yaml
  pkg/controllers/osc/testdata/secret-flatcar-aws-containerd-provisioning.yaml
Labels: lgtm, release-note, approved, sig/cluster-management, dco-signoff: yes, size/S

#485 [release/v1.6] Bump default OSPs to v1.6.7
  deploy/osps/default/osp-amzn2.yaml
  deploy/osps/default/osp-flatcar-cloud-init.yaml
  deploy/osps/default/osp-flatcar.yaml
  deploy/osps/default/osp-rhel.yaml
  deploy/osps/default/osp-rockylinux.yaml
  deploy/osps/default/osp-ubuntu.yaml
  pkg/controllers/osc/testdata/osp-rhel-aws-cloud-init-modules.yaml
Labels: release-note-none, lgtm, approved, sig/cluster-management, dco-signoff: yes, size/S, kind/chore
